apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent:windowsservercore-1809
    #image: jenkins/inbound-agent:nanoserver-1809
    securityContext:
      windowsOptions:
        runAsUserName: "ContainerAdministrator"
  - name: shell
    #image: mcr.microsoft.com/powershell:preview-windowsservercore-1809
    image: mcr.microsoft.com/dotnet/framework/sdk:4.7.2-windowsservercore-ltsc2019
    resources:
    command:
    - powershell
    args:
    - Start-Sleep
    - 999999
    tty: true
  nodeSelector:
    kubernetes.io/os: windows
  tolerations:
  - key: "os"
    operator: "Equal"
    value: "windows"
    effect: "NoSchedule"